[project]
name = "siginf-2026"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "ipywidgets>=8.1.8",
    "matlab>=0.1",
    "matplotlib>=3.10.8",
    "meteostat>=2.1.4",
    "notebook>=7.5.3",
    "numpy>=2.4.2",
    "opencv-python>=4.13.0.92",
    "plotly>=6.6.0",
    "requests>=2.32.5",
    "scipy>=1.17.1",
    "seaborn>=0.13.2",
    "tqdm>=4.67.3",
]
